site_name: Bpipe Documentation
repo_url: https://github.com/ssadedin/bpipe
theme: bootstrap
pages:
- ['index.md', 'Introduction']
- ['GettingStarted.md', 'Tutorials', 'Hello, World']
- ['ExampleWithInputsAndOutputs.md', 'Tutorials', 'Inputs and Outputs']
- ['RealPipelineTutorial.md', 'Tutorials', 'A Real Bioinformatics Pipeline']
markdown_extensions: [codehilite,extra]

